name: Post welcome comment

on:
    pull_request:
        types: [opened]

permissions:
    pull_requests: write


jobs:
    build:
        name: Post welcome comment
        runs-on: ubuntu-latest

        steps:
            - name: Test Step
              run: gh pr comment $PR_URL --body "Welcome to this repo!"
              env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                PR_URL: ${{github.event.pull_request.html_url}}